'use client';
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useMemo, useState, useTransition } from 'react';
import { Search, ShoppingCart, ChevronDown, ChevronUp, Plus, X } from 'lucide-react';
import { cancelOrder, updateOrderStatus } from '@/app/[locale]/admin/orders/actions';
import { parseOrderNotes } from '@/lib/order-notes';

const statuses = ['pending', 'confirmed', 'processing', 'shipped', 'completed', 'cancelled', 'payment_required', 'payment_failed', 'payment_expired'];
const labels: Record<string, string> = { pending: 'Chờ xử lý', confirmed: 'Đã xác nhận', processing: 'Đang xử lý', shipped: 'Đã giao', completed: 'Hoàn tất', cancelled: 'Đã hủy', payment_required: 'Chờ thanh toán', payment_failed: 'TT thất bại', payment_expired: 'TT hết hạn' };
const paymentLabels: Record<string, string> = { none: '—', pending: 'Đang chờ', success: 'Thành công', failed: 'Thất bại', expired: 'Hết hạn' };
const paymentColors: Record<string, string> = { none: 'text-slate-400', pending: 'text-amber-600', success: 'text-emerald-600', failed: 'text-red-600', expired: 'text-slate-500' };
const money = (n: number) => new Intl.NumberFormat('vi-VN').format(Number(n || 0)) + 'đ';

export default function OrdersClient({ initialOrders, availableSkus, error }: { initialOrders: any[]; availableSkus: any[]; error?: string }) {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState('all'); const [expanded, setExpanded] = useState<number | null>(null); const [isPending, startTransition] = useTransition(); const [createOpen, setCreateOpen] = useState(false); const [createError, setCreateError] = useState(''); const [form, setForm] = useState({ fullName: '', email: '', phone: '', address: '', skuId: '', quantity: '1' });
  const filtered = useMemo(() => initialOrders.filter(o => (status === 'all' || o.status === status) && `${o.code} ${o.customer?.name || ''} ${o.customer?.email || ''}`.toLowerCase().includes(query.toLowerCase())), [initialOrders, query, status]);
  const createOrder = (event: React.FormEvent) => { event.preventDefault(); setCreateError(''); const sku = availableSkus.find(x => String(x.id) === form.skuId); if (!sku) return setCreateError('Vui lòng chọn SKU'); startTransition(async () => { try { const quantity = Number(form.quantity); const price = Number(sku.price || 0); const response = await fetch('/api/orders', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ buyer: { fullName: form.fullName, email: form.email, phone: form.phone, address: form.address }, paymentMethod: 'mock', shippingMethod: 'admin', subtotal: price * quantity, tax: 0, total: price * quantity, items: [{ sku: sku.sku_code, productName: sku.product?.name || sku.sku_code, quantity, unitPrice: price, lineTotal: price * quantity }] }) }); if (!response.ok) throw new Error('Không thể tạo order'); setCreateOpen(false); window.location.reload(); } catch (err) { setCreateError(err instanceof Error ? err.message : 'Không thể tạo order'); } }); };
  return <div className="admin-page space-y-5">
    <div className="admin-header flex items-center justify-between border-b border-slate-100 pb-5"><div className="flex items-center gap-3"><ShoppingCart className="h-7 w-7 text-brand" /><div><h1 className="text-2xl font-bold text-slate-900">Quản lý Order</h1><p className="text-sm text-slate-500 mt-1">Theo dõi và cập nhật các đơn hàng từ khách hàng.</p></div></div><button onClick={() => setCreateOpen(true)} className="admin-button admin-button-primary"><Plus className="h-4 w-4" />Tạo order</button></div>
    {error && <div className="rounded border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <div className="flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Tìm mã order, tên hoặc email..." className="w-full rounded border border-slate-200 py-2.5 pl-9 pr-3 text-sm" /></div><select value={status} onChange={e => setStatus(e.target.value)} className="rounded border border-slate-200 px-3 py-2.5 text-sm"><option value="all">Tất cả trạng thái</option>{statuses.map(s => <option key={s} value={s}>{labels[s]}</option>)}</select></div>
    <div className="admin-table-wrapper"><table className="admin-table min-w-[1050px]"><thead><tr className="admin-table-head"><th className="admin-table-cell">Mã order</th><th className="admin-table-cell">Ngày đặt</th><th className="admin-table-cell">Khách hàng</th><th className="admin-table-cell">Tổng tiền</th><th className="admin-table-cell">Trạng thái</th><th className="admin-table-cell">Thanh toán</th><th className="admin-table-cell text-right">Thao tác</th></tr></thead><tbody>{filtered.map(o => { const meta = parseOrderNotes(o.notes); return <tr key={o.id} className="admin-table-row"><td className="admin-table-cell font-bold text-brand">{o.code}</td><td className="admin-table-cell">{o.order_date ? new Date(o.order_date).toLocaleDateString('vi-VN') : '-'}</td><td className="admin-table-cell"><div className="font-medium">{o.customer?.name || meta.buyer?.fullName || 'Khách vãng lai'}</div><div className="text-xs text-slate-500">{o.customer?.email || meta.buyer?.email || '-'}</div></td><td className="admin-table-cell font-semibold">{money(o.total)}</td><td className="admin-table-cell"><select disabled={isPending || o.status === 'cancelled'} value={o.status} onChange={e => startTransition(() => updateOrderStatus(o.id, e.target.value))} className="rounded border border-slate-200 px-2 py-1.5 text-xs">{statuses.map(s => <option key={s} value={s}>{labels[s]}</option>)}</select></td><td className="admin-table-cell"><span className={`text-xs font-semibold ${paymentColors[o.payment_status || 'none'] || 'text-slate-400'}`}>{paymentLabels[o.payment_status || 'none'] || '—'}</span></td><td className="admin-table-cell text-right"><div className="inline-flex items-center gap-3"><a href={`/vi/admin/orders/${o.id}`} className="text-sm text-brand font-semibold hover:underline">Chi tiết</a><button onClick={() => setExpanded(expanded === o.id ? null : o.id)} className="text-sm text-brand">{expanded === o.id ? 'Ẩn' : 'Xem'} {expanded === o.id ? <ChevronUp className="inline h-4 w-4" /> : <ChevronDown className="inline h-4 w-4" />}</button>{o.status !== 'cancelled' && <button disabled={isPending} onClick={() => { if (window.confirm(`Hủy order ${o.code}? Tồn kho sẽ được hoàn trả.`)) startTransition(async () => { await cancelOrder(o.id); window.location.reload(); }); }} className="text-sm font-semibold text-red-600 disabled:opacity-50">Hủy order</button>}</div></td></tr>; })}{!filtered.length && <tr><td colSpan={7} className="p-10 text-center text-slate-500">Chưa có order phù hợp.</td></tr>}</tbody></table></div>
    {expanded && (() => { const o = initialOrders.find(x => x.id === expanded); if (!o) return null; const meta = parseOrderNotes(o.notes); return <div className="rounded border border-slate-200 bg-white p-5"><h2 className="font-bold text-lg">Chi tiết {o.code}</h2><p className="mt-2 text-sm text-slate-600">Địa chỉ: {meta.buyer?.address || '-'} · SĐT: {meta.buyer?.phone || '-'}</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><tbody>{(o.items || []).map((i: any) => <tr key={i.id} className="border-b border-slate-100"><td className="py-2">{i.sku?.sku_code || i.description}</td><td className="py-2">SL: {i.qty}</td><td className="py-2 text-right">{money(i.line_total)}</td></tr>)}</tbody></table></div></div>; })()}
    {createOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/30 p-4"><form onSubmit={createOrder} className="w-full max-w-lg rounded-[6px] bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Tạo order thủ công</h2><button type="button" onClick={() => setCreateOpen(false)}><X className="h-5 w-5" /></button></div>{createError && <p className="mt-3 rounded bg-red-50 p-2 text-sm text-red-600">{createError}</p>}<div className="mt-4 grid gap-3 sm:grid-cols-2"><input required placeholder="Họ tên" value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })} className="admin-input" /><input required type="email" placeholder="Email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} className="admin-input" /><input required placeholder="Số điện thoại" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} className="admin-input" /><input required placeholder="Địa chỉ giao hàng" value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} className="admin-input sm:col-span-2" /><select required value={form.skuId} onChange={e => setForm({ ...form, skuId: e.target.value })} className="admin-select sm:col-span-2"><option value="">Chọn SKU</option>{availableSkus.map(s => <option key={s.id} value={s.id}>{s.sku_code} · {s.product?.name || '-'} · {money(s.price)}</option>)}</select><input required min="1" type="number" placeholder="Số lượng" value={form.quantity} onChange={e => setForm({ ...form, quantity: e.target.value })} className="admin-input" /></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setCreateOpen(false)} className="admin-button">Hủy</button><button disabled={isPending} className="admin-button admin-button-primary">{isPending ? 'Đang tạo...' : 'Tạo order'}</button></div></form></div>}
  </div>;
}
