'use client';
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useMemo, useState, useTransition } from 'react';
import { Search, ShoppingCart, ChevronDown, ChevronUp } from 'lucide-react';
import { updateOrderStatus } from '@/app/[locale]/admin/orders/actions';

const statuses = ['pending', 'confirmed', 'processing', 'shipped', 'completed', 'cancelled'];
const labels: Record<string, string> = { pending: 'Chờ xử lý', confirmed: 'Đã xác nhận', processing: 'Đang xử lý', shipped: 'Đã giao', completed: 'Hoàn tất', cancelled: 'Đã hủy' };
const money = (n: number) => new Intl.NumberFormat('vi-VN').format(Number(n || 0)) + 'đ';

export default function OrdersClient({ initialOrders, error }: { initialOrders: any[]; error?: string }) {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState('all'); const [expanded, setExpanded] = useState<number | null>(null); const [isPending, startTransition] = useTransition();
  const filtered = useMemo(() => initialOrders.filter(o => (status === 'all' || o.status === status) && `${o.code} ${o.customer?.name || ''} ${o.customer?.email || ''}`.toLowerCase().includes(query.toLowerCase())), [initialOrders, query, status]);
  return <div className="space-y-6">
    <div className="admin-header border-b border-slate-100 pb-6"><div className="flex items-center gap-3"><ShoppingCart className="h-7 w-7 text-brand" /><div><h1 className="text-2xl font-bold text-slate-900">Quản lý Order</h1><p className="text-sm text-slate-500 mt-1">Theo dõi và cập nhật các đơn hàng từ khách hàng.</p></div></div></div>
    {error && <div className="rounded border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <div className="flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Tìm mã order, tên hoặc email..." className="w-full rounded border border-slate-200 py-2.5 pl-9 pr-3 text-sm" /></div><select value={status} onChange={e => setStatus(e.target.value)} className="rounded border border-slate-200 px-3 py-2.5 text-sm"><option value="all">Tất cả trạng thái</option>{statuses.map(s => <option key={s} value={s}>{labels[s]}</option>)}</select></div>
    <div className="admin-table-wrapper"><table className="admin-table min-w-[950px]"><thead><tr className="admin-table-head"><th className="admin-table-cell">Mã order</th><th className="admin-table-cell">Ngày đặt</th><th className="admin-table-cell">Khách hàng</th><th className="admin-table-cell">Tổng tiền</th><th className="admin-table-cell">Trạng thái</th><th className="admin-table-cell text-right">Chi tiết</th></tr></thead><tbody>{filtered.map(o => <tr key={o.id} className="admin-table-row"><td className="admin-table-cell font-bold text-brand">{o.code}</td><td className="admin-table-cell">{o.order_date ? new Date(o.order_date).toLocaleDateString('vi-VN') : '-'}</td><td className="admin-table-cell"><div className="font-medium">{o.customer?.name || JSON.parse(o.notes || '{}').buyer?.fullName || 'Khách vãng lai'}</div><div className="text-xs text-slate-500">{o.customer?.email || JSON.parse(o.notes || '{}').buyer?.email || '-'}</div></td><td className="admin-table-cell font-semibold">{money(o.total)}</td><td className="admin-table-cell"><select disabled={isPending} value={o.status} onChange={e => startTransition(() => updateOrderStatus(o.id, e.target.value))} className="rounded border border-slate-200 px-2 py-1.5 text-xs">{statuses.map(s => <option key={s} value={s}>{labels[s]}</option>)}</select></td><td className="admin-table-cell text-right"><button onClick={() => setExpanded(expanded === o.id ? null : o.id)} className="inline-flex items-center gap-1 text-sm text-brand">{expanded === o.id ? 'Ẩn' : 'Xem'} {expanded === o.id ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}</button></td></tr>)}{!filtered.length && <tr><td colSpan={6} className="p-10 text-center text-slate-500">Chưa có order phù hợp.</td></tr>}</tbody></table></div>
    {expanded && (() => { const o = initialOrders.find(x => x.id === expanded); if (!o) return null; let meta: any = {}; try { meta = JSON.parse(o.notes || '{}'); } catch {} return <div className="rounded border border-slate-200 bg-white p-5"><h2 className="font-bold text-lg">Chi tiết {o.code}</h2><p className="mt-2 text-sm text-slate-600">Địa chỉ: {meta.buyer?.address || '-' } · SĐT: {meta.buyer?.phone || '-'}</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><tbody>{(o.items || []).map((i: any) => <tr key={i.id} className="border-b border-slate-100"><td className="py-2">{i.sku?.sku_code || i.description}</td><td className="py-2">SL: {i.qty}</td><td className="py-2 text-right">{money(i.line_total)}</td></tr>)}</tbody></table></div></div>; })()}
  </div>;
}
